---
title: "fire_explore"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSocrata)
library(tidyverse)
library(zipcode)
library(plotly)
```

```{r load, cache = TRUE}
with_detail = read.socrata("https://data.cityofnewyork.us/resource/ibte-hq4u.csv")
#without_detail = read.socrata("https://data.cityofnewyork.us/resource/mhu7-c3xb.csv")
```

```{r explore}
data("zipcode")
zipcode = zipcode %>% 
  rename(zip_code = zip)
str(with_detail)

##check if some incidents do not have information about incident time
sum(is.na(with_detail$incident_date_time))
sum(is.na(without_detail$incident_datetime))

##duplicate the dataset to have an original copy
dupli_with = with_detail
dupli_without = without_detail %>% 
                rename(incident_date_time = incident_datetime)

#check if some incidents happen at the same time
dupli_with %>% 
  group_by(incident_date_time) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))
dupli_without %>% 
  group_by(incident_date_time) %>% 
  summarize(n = n()) %>% 
  arrange(desc(n))

#join two data sets
new_full = full_join(dupli_with, dupli_without, by = "incident_date_time")

#create new nata set with coordinates
with_cor = left_join(dupli_with, zipcode, by = "zip_code")

set.seed(1)
as.character(dupli_without$starfire_incident_id[[1]])


##number of incidence in each zipcode area in Manhattan
with_cor %>% 
  filter(borough_desc == "1 - Manhattan") %>% 
  mutate(latitude = latitude +  0.0015 * rnorm(582136, 0, 1),
         longitude = longitude +  0.0015 * rnorm(582136, 0, 1)) %>% 
  group_by(zip_code) %>% 
  mutate(count_in_zip = n()) %>% 
  ggplot(aes(x = longitude, y = latitude)) +
    geom_point(aes(color = count_in_zip), size = 0.015) +
    theme_bw()

##all cities
with_cor %>% 
  mutate(latitude = latitude +  0.0015 * rnorm(2277779, 0, 1),
         longitude = longitude +  0.0015 * rnorm(2277779, 0, 1)) %>% 
  group_by(zip_code) %>% 
  mutate(count_in_zip = n()) %>% 
  ggplot(aes(x = longitude, y = latitude)) +
    geom_point(aes(color = count_in_zip), size = 0.015) +
    theme_bw()
```

```{r zipcode_map}
install_github('arilamstein/choroplethrZip@v1.3.0')
library(choroplethrZip)

zip_map_data = 
  dupli_with %>% 
  group_by(zip_code) %>% 
  summarise(value = n()) %>% 
  slice(2:181) %>% 
  filter(zip_code !="10691" & zip_code != "11209-0000" &zip_code != "11251") %>% 
  rename(region = zip_code)

zip_map_data %>% 
ggplot(aes(x = value)) +
  geom_histogram()

zip_choropleth(zip_map_data, 
               zip_zoom = zip_map_data$region, 
               title      = "Fire alarm incidence in New York",
               legend     = "Fire count") + coord_map()

```

```{r explore_property_use} 
dupli_with %>% 
  group_by(property_use_desc) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% View()
```

```{r explore_asso_season_cause}
asso_sea_cause = 
  with_detail %>% 
  select(incident_date_time, incident_type_desc, 
         property_use_desc, zip_code, borough_desc) %>% 
  #get a clean borough variable
  separate(borough_desc, sep = "- ", into = c("n", "borough")) %>% 
  select(-n) %>% 
  #make it easier to filter true fire alarms
  separate(incident_type_desc, into = c("incident_type", "incident_desc"), sep = "- ") %>%
  mutate(incident_type = str_sub(incident_type, 1, 3),
         incident_type = as.integer(incident_type)) %>% 
  #clean year and month
  mutate(month = as.factor(month.abb[as.integer(substr(incident_date_time, 6, 7))]),
         month = fct_relevel(month, "Jan", "Feb", "Mar", "Apr", "May", 
                             "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"), 
         year = str_sub(incident_date_time, 1, 4)) %>% 
  #get a season variable. I can't believe I'm using this ugly if_else
  mutate(season = 
           if_else(month %in% c("Dec", "Jan", "Feb"), "winter", 
                   if_else(month %in% c("Mar", "Apr", "May"), "spring", 
                           if_else(month %in% c("Jun", "Jul", "Aug"), "summer", "autumn"))), 
         season = as.factor(season), 
         season = fct_relevel(season, c("summer", "autumn", "spring", "winter"))) %>% 
  #clean zip code, exclude unreasonable zip codes
  mutate(zip_code = str_sub(zip_code, 1, 5)) %>% 
  filter(zip_code != "" & zip_code != "99999" & 
         zip_code != "10691" & zip_code != "11251", 
         incident_type < 165)

##how many observations without zipcode
with_detail %>% 
  group_by(zip_code) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count))

##The most frequent cause in each season
asso_sea_cause %>% 
  filter(season == "summer") %>%
#  summarise(n = n()) %>% 
  group_by(incident_desc) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  mutate(percentage = round(count /  39494, digits = 4))
asso_sea_cause %>% 
  filter(season == "winter") %>% 
#  summarize(n = n())
  group_by(incident_desc) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  mutate(percentage = round(count /  46800, digits = 4))
asso_sea_cause %>% 
  filter(season == "spring") %>%
#    summarize(n = n())
  group_by(incident_desc) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
    mutate(percentage = round(count /  47097, digits = 4))
asso_sea_cause %>% 
  filter(season == "autumn") %>% 
  #summarize(n = n())
  group_by(incident_desc) %>% 
  summarise(count = n()) %>% 
  arrange(desc(count)) %>% 
  mutate(percentage = round(count /  44447, digits = 4))

asso_sea_cause %>% 
  group_by(season, property_use_desc) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count)) %>% 
  mutate(percentage = round(if_else(season == "summer", count/39494, 
                              if_else(season == "winter", count/46800, 
                                      if_else(season == "spring", count/47097, count/44447))) ,digits = 2))

cause_hour_plot = 
  asso_sea_cause %>% 
  mutate(hour = str_sub(incident_date_time, 12, 13), 
         hour = as.integer(hour)) %>% 
  group_by(hour, incident_desc) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count)) %>% 
  ggplot(aes(x = hour, y = count)) +
  geom_line(aes(color = incident_desc))+ 
  theme_classic() +
  theme(legend.position = "none")
ggplotly(cause_hour_plot)

asso_sea_cause%>% 
  group_by(month, property_use_desc) %>%   
  summarize(count = n()) %>% 
  arrange(desc(count)) %>%
  filter(count > 2000) %>% 
  ggplot(aes(x = month, y = count)) +
  geom_col(aes(fill = property_use_desc)) +
  theme_classic() +
  theme(legend.position = "none") +
  facet_wrap(~ property_use_desc) 


asso_sea_cause%>% 
  drop_na(month) %>% 
  filter(incident_type %in% c(113, 151)) %>% 
  group_by(month, incident_desc) %>%   
  summarize(count = n()) %>% 
  arrange(desc(count)) %>% 
  ggplot(aes(x = month, y = count)) +
  geom_col(aes(fill = incident_desc)) +
  theme_classic() +
  theme(legend.position = "none") +
  facet_wrap(~ incident_desc) 

```

