---
title: "fire_factors"
output: github_document
---

---
title: "fire_incidence_project"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(RSocrata)
library(plotly)
```

```{r read_data, cache = TRUE}
# load data from online source

fire_data = read.socrata("https://data.cityofnewyork.us/resource/ibte-hq4u.csv") %>%
  janitor::clean_names()
```

```{r count_by_incident_type}
# count the frequency of the specific description of incidents and plot with order

fire_factor1 = fire_data %>%
  group_by(incident_type_desc) %>%
  summarize(count = n()) %>%
  arrange(desc(count)) %>%
  ungroup() %>% 
  separate(incident_type_desc, into = c("incident_type", "incident_desc"), sep = "-") %>% 
  mutate(incident_type = str_sub(incident_type, 1, 3), 
         incident_type = as.integer(incident_type),
    incident_desc = forcats::fct_reorder(incident_desc, count))

fire_factor1 %>%
  filter(incident_type >= 100 & incident_type <=199) %>% 
  filter(count > 100) %>%
  select(-incident_type) %>% 
  knitr::kable()

fire_factor1 %>%
  filter(incident_type >= 100 & incident_type <=199) %>% 
  filter(count > 100) %>% 
  ggplot(aes(x = incident_desc, y = count)) +
  geom_col() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 55, hjust = 1, size = 9)) +
  labs(title = "Frequency for Contributing Factors of True Fire Alarm",
       x = "Contributing Factors",
       y = "Frequency",
       caption = "Data provided by Fire Department of New York City (FDNY)")


```


```{r add_time}
asso_sea_cause = 
  fire_data %>% 
  select(incident_date_time, incident_type_desc, 
         property_use_desc, zip_code, borough_desc) %>% 
  separate(borough_desc, sep = "- ", into = c("n", "borough")) %>% 
  select(-n) %>% 
  separate(incident_type_desc, into = c("incident_type", "incident_desc"), sep = "- ") %>%
  mutate(incident_type = str_sub(incident_type, 1, 3),
         incident_type = as.integer(incident_type)) %>% 
  mutate(month = as.factor(month.abb[as.integer(substr(incident_date_time, 6, 7))]),
         month = fct_relevel(month, "Jan", "Feb", "Mar", "Apr", "May", 
                             "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"), 
         year = str_sub(incident_date_time, 1, 4)) %>% 
  filter(zip_code != "" & zip_code != "99999" & 
         zip_code != "10691" & zip_code != "11251", 
         incident_type < 165) %>% 
  mutate(hour = str_sub(incident_date_time, 12, 13), 
         hour = as.integer(hour)) %>%
  separate(property_use_desc, sep = "- ", into = c("n", "property_use_desc")) %>% 
  select(-n)
```

```{r plots}
cause_hour_plot = 
  asso_sea_cause %>% 
  group_by(hour, incident_desc) %>% 
  summarize(count = n()) %>% 
  arrange(desc(count)) %>% 
  ggplot(aes(x = hour, y = count)) +
  geom_line(aes(color = incident_desc))+ 
  theme_classic() +
  theme(legend.position = "none") +
  labs(title = "Frequency for Contributing Factors of True Fire Alarm in Each Hour",
       x = "Time",
       y = "Frequency",
       caption = "Data provided by Fire Department of New York City (FDNY)")
ggplotly(cause_hour_plot)

asso_sea_cause%>% 
  group_by(month, property_use_desc) %>%   
  summarize(count = n()) %>% 
  arrange(desc(count)) %>%
  filter(count > 2000) %>% 
  ggplot(aes(x = month, y = count)) +
  geom_col(aes(fill = property_use_desc)) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(title = "Frequency for Two Top Property Use of True Fire Alarm",
       x = "Month",
       y = "Frequency",
       caption = "Data provided by Fire Department of New York City (FDNY)") +
  facet_wrap(~ property_use_desc) 


asso_sea_cause%>% 
  drop_na(month) %>% 
  filter(incident_type %in% c(113, 151)) %>% 
  group_by(month, incident_desc) %>%   
  summarize(count = n()) %>% 
  arrange(desc(count)) %>% 
  ggplot(aes(x = month, y = count)) +
  geom_col(aes(fill = incident_desc)) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(title = "Frequency for Contributing Factors of True Fire Alarm in Each Month",
       x = "Month",
       y = "Frequency",
       caption = "Data provided by Fire Department of New York City (FDNY)") +
  facet_wrap(~ incident_desc) 
```

