---
title: "count_over_time"
author: Yuxin
date: Dec. 1, 2018
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(RSocrata)
library(tidyverse)
```

```{r load, cache = TRUE}
with_detail = read.socrata("https://data.cityofnewyork.us/resource/ibte-hq4u.csv")
```

```{r tidy}
analysis = with_detail %>%
  janitor::clean_names() %>%
  separate(arrival_date_time, into = c("date", "time"), sep = " ") %>%
  separate(date, into = c("year", "month", "date"), sep = "-") %>%
  separate(time, into = c("hour", "minute", "second"), sep = ":") %>%
  separate(borough_desc, into = c("code", "city", sep = " - ")) %>%
  mutate(index = substr(incident_type_desc, 1, 3),
         year = as.integer(year), 
         month = as.integer(month), 
         date = as.integer(date), 
         hour = as.integer(hour), 
         minute = as.integer(minute), 
         second = as.integer(second), 
         index = as.integer(index)
        ) %>%
  filter(index < 200 & index >99)
```

```{r change_month}
analysis_adj = analysis %>%
   mutate(month = str_replace(month, "3", "Spring"),
          month = str_replace(month, "4", "Spring"),
          month = str_replace(month, "5", "Spring"),
          month = str_replace(month, "6", "Summer"),
          month = str_replace(month, "7", "Summer"),
          month = str_replace(month, "8", "Summer"),
          month = str_replace(month, "9", "Autumn"),
          month = str_replace(month, "10", "Autumn"),
          month = str_replace(month, "11", "Autumn"),
          month = str_replace(month, "12", "Winter"),
          month = str_replace(month, "1", "Winter"),
          month = str_replace(month, "2", "Winter"),
          month = fct_relevel(month, "Spring"))
```

```{r plot}
analysis %>%
  group_by(hour, city) %>%
  summarize(n = n()) %>%
  ggplot(aes(x = hour, y = n, color = city)) +
  geom_line() +
  labs(title = "Number of Fire incident according to hours") +
    theme(panel.grid.major = element_blank(), 
          panel.grid.minor = element_blank(),
          panel.background = element_blank(), 
          axis.line = element_line(colour = "black"))
```
