---
title: "Project Proposal"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

###Group members
Jiawei Ye (jy2947), Yuxin Yang(yy2926), Ruoyu Ji, Lingyu Zhang

### The tentative project title

Factors Associated with Fire Accidents in New York City from 2015 to 2017

###Motivation

The story starts on a peaceful weekend night, 100 Haven Avenue, Tower 3.  

The fire alarm went off. AT 2A.M. 

The residents were woken up from their sweet dreams and had to rush downstairs in bewilderment. Nothing seemed to be wrong in this building. No heat, no smoke. No sign of fire or danger.   

The firemen arrived in minutes. The good news was they didn't need to risk their lives to rescue anyone from fire, the bad news was they still had to make sure nothing went wrong in this building at 2 o'clock in midnight.  

But there was nothing wrong - except for an open door that should not be opened on the rooftop.  

Someone began wondering - how often does incidents like this happen in NYC? 

This is the very start of this final project.  

### Intended final products

Our final product will be a website which contains analyses of the possible factors associated with fire incidents. The contents will include the introduction page of our project. Visualization page of mapping the Fire incident reports and the effect of different possible factors. Analysis page of final statistics model. Moreover, we intend to incorporate a screencast of background information of our project.

### The anticipated data sources

First data source URL: https://data.cityofnewyork.us/Public-Safety/Fire-Incident-Dispatch-Data/8m42-w767 

Data is provided by the Fire Department of New York City (FDNY), and last updated by 09/13/2018. It is generated by the Starfire Computer Aided Dispatch System, covering information about the incident as it relates to the assignment of resources and the Fire Department’s response to the emergency. However, the data doesn’t contain a detailed description of the causes of the fire incident.

Second data source URL: https://data.cityofnewyork.us/Public-Safety/Incidents-Responded-to-by-Fire-Companies/tm6d-hbzd

Data is provided by the Fire Department of New York City (FDNY), and last updated by 09/10/2018. Though the New York Fire Incident Reporting System (NYFIRS) was designed specifically to understand the nature and causes of fire, as well as civilian fire casualties and firefighter injuries, it has been expanded to collect basic information on all incidents.


### The planned analyses/visualizations/coding challenges
Planned analyses:  
The most common causes of fire incidents. 
The locations of the fire incidences by zip code area. 
The respond time of the fire department by zip code area. 
Use statistical models to analyze the factors associated with fire incidents and mortality. 
Possibly scrap the web for news of major fire incidence and “cross-validated” with the data we have. 

Visualizations: 
Maps: The area with the most fire incidences. The area with the fastest responses from the fire department. 
Bar chart - The most common causes of fire incidents. 

Coding challenges:
There are no coordinates of the exact location of the fire, so we have to use zip code or street names to visualize the incidence of fire. We currently do not know if it is easy to accomplish.


### The planned timeline

~Nov. 8 Write the proposal
Nov. 9 ~ Nov. 16 Finish the preliminary work
Nov. 17 ~ Dec. 5 Collect and clean the data, do exploratory analyses, alternative strategies, describe the approaches and discuss the results
